### ISSUE TITLE
Allow multiple vaults/auths

### ISSUE THREAD

**Issue by fishi0x01** [fishi0x01/saidumlo#13]
```
---
vaults:
  qa:
    address: "http://127.0.0.1:8200"
    bin: "bin/vault"
    auth:
      backend: "github"
      token: "blub"
  live:
    address: "http://127.0.0.1:8300"
    bin: "bin/vault"
    auth:
      backend: "github"
      token: "blab"

groups:
  qa:
    vault: "qa"
    secrets:
    - local: "test/qa-foo"
      vault: "secret/test/qa-foo"
    - local: "test/qa-bar"
      vault: "secret/test/qa-bar"

  prod:
    vault: "live"
    secrets:
    - local: "test/prod-foo"
      vault: "secret/test/qa-foo"
    - local: "test/prod-bar"
      vault: "secret/test/qa-bar"
```
