### ISSUE TITLE
Secret mappings can be used by multiple vault backends

### ISSUE THREAD

**Issue by fishi0x01** [fishi0x01/saidumlo#19]
e.g.,:
```
vaults:
  vault-a:
    ..
    secrets:
    - qa

secrets:
  qa:
  - local: ...
  live:
```

Useful if the same vault backend has many different URLs
