### ISSUE TITLE
Flag to store binary content

### ISSUE THREAD

**Issue by fishi0x01** [fishi0x01/saidumlo#31]
Binary content such as .zip files must be converted to base64 first in order to be stored in vault. 

Might look like that:
```
zip-files:
  base64: true
  mappings:
  - local: ..
    vault: ..
```
